[project]
name = "test-webrtc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.13",
    "aiortc>=1.10.1",
    "opencv-python>=4.11.0.86",
    "websockets>=15.0.1",
]
